name: climabrasil
description: Aplicativo de clima focado no Brasil com design premium.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5
  fl_chart: ^0.70.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
